name: Deploy AWS

on:
  push:
    branches: [main, master]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: terraform-production
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: [self-hosted, windows]

    defaults:
      run:
        working-directory: src

    env:
      AWS_DEFAULT_REGION: us-east-1
      TF_VAR_rds_password: ${{ secrets.TF_VAR_rds_password }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check AWS session
        run: aws sts get-caller-identity

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform init
        run: terraform init

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        run: terraform plan

      - name: Terraform apply
        run: terraform apply -auto-approve